on: 
  push:
    branchs:
      - main
name: ðŸš€ Deploy website on push
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'lxtec'
          server: '207.244.248.118'
          port: '37950'
          ssh_private_key: 'SkyLin3@1999'
          local_path: './static/*'
          remote_path: 'var/www/html/LxProcessos/demoprcss/github-actions/'
          args: '-o ConnectTimeout=10'